### ISSUE TITLE
Jasmine Reporter is compatible with Protractor 5.0 and Jasmine 2.5.3?

### ISSUE THREAD

**Issue by Kappyh** [bcaudan/jasmine-spec-reporter#111]
Hi,

In the last few day Im trying run my tests and view the reports with your tool, but I have done exactly like the readme and my terminal dont show the specs reports with Jasmine Reporter.
Jasmine Reporter is compatible with Protractor 5.0.0 and Jasmine 2.5.3?

Thank you :)

**Comment by bcaudan** [comment]
I have an integration test running with the latest version of protractor and jasmine, so it is supposed to work :)
You could try to run the protractor example in this repository: https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/protractor#example

**Comment by Kappyh** [comment]
I found my error!(wrong constructor D:)
Thank you @bcaudan ;D
