### ISSUE TITLE
Executed Steps in NaN hour

### ISSUE THREAD

**Issue by kariasbolster** [bcaudan/jasmine-spec-reporter#156]
It displays NaN after running all the tests. See http://i.imgur.com/0W2b4YG.png

**Comment by bcaudan** [comment]
Could you clone this repository and try to reproduce this issue with this example: https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/node?

**Comment by bcaudan** [comment]
Closed due to lack of information. If you are facing this behavior, please fill a new issue.

**Comment by kariasbolster** [comment]
Sorry for not being able to reply lately. Already found the reason why. Thank you.
