### ISSUE TITLE
Output with Typescript is not correct

### ISSUE THREAD

**Issue by dhilgarth** [bcaudan/jasmine-spec-reporter#237]
## Bug report

Output is not correct. It shows "No specs found" and "npm ERR! Test failed".

- [x] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples): Typescript

**Current behavior**

Output: 
```
TypeScript Jasmine started
Started

  first suite
    √ should be ok


No specs found
Finished in 0.003 seconds

npm ERR! Test failed.  See above for more details.
```
**Expected behavior**
Output is similar to the gif in the readme

**Minimal reproduction of the problem with instructions**
Get current code from repo.
`cd examples\typescript`
`npm install`
manually remove folder `node_modules/jasmine-spec-reporter` (I am on windows and therefore `install-local-jsr` fails as `rm -rf` doesn't exist)
`npm install jasmine-spec-reporter`
`npm test`

**Comment by bcaudan** [comment]
Thanks for raising this issue.

I have updated the example and the documentation to use the same strategy as the node example and now it behaves correctly.

Have a look at the new way to configure it: [typescript example](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/typescript)
