### ISSUE TITLE
Add option to display spec file path

### ISSUE THREAD

**Issue by psprogis** [bcaudan/jasmine-spec-reporter#248]
## Feature request 

**Current behavior**
As of now spec reporter does not show file names/paths.

**Wanted behavior**
There should be option(s), like: 
`suite: {
    displayFileNames: true,
    displayFullPath: false
}`

And report will look like this:
Library tab (125 s) (library.spec.js)
✓should display 6 assets(0.142 s)
✓should find 2 assets that contain "HD" in title(0.832 s)
...

Or it may have full path:
Library tab (125 s) (library.spec.js | /vagrant/ws/aa/trunk/tests/e2eTests/specs)

**What is the motivation / use case for changing the behavior?**
It will allow to find source file with test faster, when you have a lot of suites it takes time to find origin file by spec description.

**Comment by bcaudan** [comment]
Hi @psprogis,

This feature seems interesting but it can not be handled by jasmine-spec-reporter for now.
Spec file name is not available during test execution.

There is an open issue on jasmine that could help: https://github.com/jasmine/jasmine/issues/1256
