### ISSUE TITLE
Enable limiting stack traces to failure section

### ISSUE THREAD

**Issue by pmowrer** [bcaudan/jasmine-spec-reporter#26]
The report gets pretty verbose when both stack traces and the failure section are enabled since the stack traces end up being reported twice. Personally, I think it would be easier to read the report if the stack traces were only shown in the failure section, but there's currently no combination of options that would enable this.

**Comment by gmhenderson** [comment]
+1

**Comment by bcaudan** [comment]
To limit stack traces to failure section, you could use the option:
```node
{
  displayStacktrace: 'summary',
  ...
}
```

Will be available in v2.2.0 and v1.2.0, soon to be released!
