### ISSUE TITLE
Should not force users into using yarn

### ISSUE THREAD

**Issue by th13** [bcaudan/jasmine-spec-reporter#263]
## Feature request 

**Current behavior**

Package forces user to use yarn.

**Wanted behavior**

Yarn vs NPM should be the choice of individual developers.

**What is the motivation / use case for changing the behavior?**

Yarn was developed as an OPTIONAL replacement for NPM. Even in the same repository, team members should be able to choose between using yarn or npm. Putting yarn specific commands in the build process is extremely opinionated. This package should allow contributions from all users, whether or not they're using npm or yarn.

**Comment by bcaudan** [comment]
I understand your point but unfortunately some commands that are used for build / tests in this repository behaved differently between npm and yarn.
I was using yarn myself so I choosed to support yarn only for these commands.
With improvements of npm@5, I would want to go back to npm (https://github.com/bcaudan/jasmine-spec-reporter/pull/207) but I have not achieved it yet.
