### ISSUE TITLE
Reporter incorrectly reports disabled specs as failed

### ISSUE THREAD

**Issue by clayreimann** [bcaudan/jasmine-spec-reporter#28]
Specs like:  `it('should initalize with no errors');` cause spec-reporter to report a failure when a pending spec would be more appropriate.

**Comment by bcaudan** [comment]
I can't reproduce the behaviour you describe...
This kind of spec are reported (by default or jasmine spec reporter) as:
* with jasmine1: successful
* with jasmine2: pending

I have used the example spec (`npm run example`) to test it.
Could you reproduce your your issue with it?

**Comment by bcaudan** [comment]
I finally succeed to reproduce this issue by focusing a spec:

```node
describe('suite', function() {
  fit('should be executed', function() {
  });

  it('should be skipped', function() {
  });
});
```

`Executed 1 of 2 specs SUCCESS (1 SKIPPED) in 0.042 secs.`

So in v2.2.1, disabled specs are reported as skipped.
