### ISSUE TITLE
Documentation for how to run this reporter in Node

### ISSUE THREAD

**Issue by joswhite** [bcaudan/jasmine-spec-reporter#30]
<p>I thought I'd add my two cents here, since it took me awhile to figure out how to use this in Node and I'd like to spare others the trouble. Let me point out that this plugin is AWESOME! It makes it so much nicer for me to run the tests when I want to see the output. Thank you so much. If we could get something like what I've written below added to this project's documentation (feel free to use what I wrote), that would be amazing!</p>
<p>1. You do not need to use Protractor with this reporter. If you want to simply run it in Node, add the following to your package.json file and place the run-example.js (in this project's example folder) in your Jasmine spec folder:</p>
<pre><code>"scripts": {
    "test": "node ./spec/run-example.js"
  }</code></pre>
<p>2. A really easy way to get this working if you already have the jasmine.json config file is to change a few lines of the run-example.js as shown below. If your config file already has regex to specify spec and helpers file, then Jasmine will add these files automatically. It's unfortunate that it seems nearly impossible to find documentation on these methods from Jasmine, but I found that looking up the code itself in the <code>node_modules/jasmine</code> module made it a lot easier to decide which methods to use.</p>
<pre><code>...
var SpecReporter = require('jasmine-spec-reporter');    //different code
...
jasmine.getEnv().addReporter(...);    //same code

jrunner.projectBaseDir = path.resolve('.');    //different code
jrunner.specDir = 'spec';
jrunner.loadConfigFile();
jrunner.execute();</code></pre>
<p>Hope this is helpful in setting up your jasmine-spec-reporter project. Good luck!</p>

**Comment by bcaudan** [comment]
Thanks a lot for your feedback!

I also struggled when I set up tests with jasmine-npm, so it is a really great idea to document it!
I've just add a [jasmine node configuration](docs/jasmine-npm-configuration.md) section in the documentation.

I'll be glad if you can take a look, feel free to improve it through a PR ;)

**Comment by joswhite** [comment]
Looks good to me. Thanks for doing that!

**Comment by centigrade-thomas-becker** [comment]
I am trying to get this reporter to run with nodejs. I've created the file `jasmine-runner.js` inside the folder `spec`. My jasmine.json lies in `spec/support`.

If I try to run this reporter with `node spec/jasmine-runner.js` the only output I see is `Spec started`, and nothing else.

**Comment by bcaudan** [comment]
Have you tried with `jasmine-runner.js` not inside the folder `spec` but at the same level?

**Comment by centigrade-thomas-becker** [comment]
I added the Jasmine example tests to my project with `jasmine examples`, and they are working fine:

```
Spec started

  Player
    ✓ should be able to play a Song

    when song has been paused
      ✓ should indicate that the song is currently paused
      ✓ should be possible to resume

    ✓ tells the current song if the user has made it a favorite

    #resume
      ✓ should throw an exception if song is already playing
```

I'll investigate further

**Comment by centigrade-thomas-becker** [comment]
As an aside: The little check-icon "✓" is beeing displayed as an unkown character "◻" in my default windows console. If I copy & paste the output somewhere else it looks fine.

I guess this is a windows only problem
