### ISSUE TITLE
Yarn and NPM issue: - npm ERR! code ELIFECYCLE -  error Command failed with exit code 1. 

### ISSUE THREAD

**Issue by hakamaq** [bcaudan/jasmine-spec-reporter#306]
## Bug report

Check with "x":

- [ x ] I have this issue with the latest release of [jasmine-spec-reporter](https://github.com/bcaudan/jasmine-spec-reporter/releases) 
- [  ] I have this issue with the latest release of [jasmine](https://github.com/jasmine/jasmine/releases) 
- [ x ] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples)

**Current behavior**
When running a failed jasmine test the SpecReporter exits the npm or yarn with and exit code of 1 an aggressive way to exit. I thought there was something with the code but found it is the reporter exiting. (seen in screenshot)
**Expected behavior**
Have the CLI just exit normal without the npm error or the yarn error
**Minimal reproduction of the problem with instructions**
Add the SpecReporter and execute a jasmine spec with a failed tested

![image](https://user-images.githubusercontent.com/18564465/38166237-7b97e3f4-3531-11e8-8582-3fcaad0dc3cf.png)

**Comment by bcaudan** [comment]
Hi @hakamaq,

SpecReporter is not responsible of the exit code of the process, it only produces logs.
IMO, exit 1 is a pretty standard way for a test runner to exit when there is a failure.

If you are using jasmine cli to run your tests, you can see its behavior here: [jasmine/jasmine-npm:lib/jasmine.js#L166](https://github.com/jasmine/jasmine-npm/blob/bdc7ab471f5712c11a4211ae2997fff5a249a4d1/lib/jasmine.js#L166).
