### ISSUE TITLE
All specs displayed when using fdescribe and fit

### ISSUE THREAD

**Issue by gmhenderson** [bcaudan/jasmine-spec-reporter#37]
Hello @bcaudan. I updated from Jasmine to 2.1.1 from 2.3.1 and now when running focused specs, all skipped specs are listed. With Jasmine 2.1.1, it would only show the focused specs.

![image](https://cloud.githubusercontent.com/assets/1471335/7776156/b08fbc90-006d-11e5-9007-ce640e1be808.png)

Is it possible to only show the focused spec? I am using Protractor 2.1.0 and the latest (2.2.1) version of jasmine-spec-reporter. Thanks for your work on this reporter, it has made my testing work more enjoyable.

**Comment by bcaudan** [comment]
Thanks @gmhenderson for your feedback! This issue is fixed in v2.2.2.
