### ISSUE TITLE
Pending 

### ISSUE THREAD

**Issue by obriankevin11** [bcaudan/jasmine-spec-reporter#373]
## Bug report

Check with "x":

- [x] I have this issue with the latest release of [jasmine-spec-reporter] (4.2.1) (https://github.com/bcaudan/jasmine-spec-reporter/releases) 
- [ ] I have this issue with the latest release of [jasmine](https://github.com/jasmine/jasmine/releases) 
- [ ] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples)

**Current behavior**

class CustomProcessor extends DisplayProcessor {
    constructor() {
        super({
            spec: {
                displayPending: false,
            },
            summary: {
                displayPending: false,
            }
        });
    }
...

jasmine.getEnv().addReporter(new SpecReporter({
    spec: {
        displayPending: false
    },
    customProcessors: [CustomProcessor],
}));

```
**************************************************
*                    Pending                     *
**************************************************

1) blabla 
Test should run the automatic booking
  No reason given

2) blabla2
  Temporarily disabled with xit
```

**Expected behavior**
No pending section output

**Comment by bcaudan** [comment]
Hi @obriankevin11,

By looking at the code this behavior seems normal to me.
If **you only want to disable pending summary**, you should use the configuration that is given to SpecReporter instance:

```js
jasmine.getEnv().addReporter(new SpecReporter({
  spec: {
    displayPending: false
  },
  summary: {
    displayPending: false,
  }
  customProcessors: [CustomProcessor],
}));
```

If **you want to modify the configuration with a processor**, you should not provide a new configuration object in the constructor but instead something like modifying the given configuration:

```js
class CustomProcessor extends DisplayProcessor {
  constructor(configuration) {
    configuration.summary.displayPending = false;
    super(configuration);
}
```

(not tested)

Does it make sense?

**Comment by obriankevin11** [comment]
It does :)
I didn't know the CustomProcessor was actually created with the configuration
Thank you!

**Comment by bcaudan** [comment]
You're welcome, I'll add a section on the documentation about it, it could be a bit clearer 😉

**Comment by obriankevin11** [comment]
super ! merci encore cher concitoyen ! (j'avais pas vu que tu es français :))
