### ISSUE TITLE
Disabled specs are reported as failed (as of Jasmine 2.3.x?) 

### ISSUE THREAD

**Issue by pmowrer** [bcaudan/jasmine-spec-reporter#38]
After upgrading Jasmine from 2.1.1 to 2.3.1 (actually, [Protractor did this for us](https://github.com/angular/protractor/blob/master/CHANGELOG.md#210), we cannot control the exact Jasmine version), disabled tests are reported as failed (i.e. `xdescribe` and `xit`). 

Maybe its a bug in Jasmine itself? https://github.com/jasmine/jasmine/issues/840

Sorry if double-reporting, I saw issue https://github.com/bcaudan/jasmine-spec-reporter/issues/28 but it made not explicit mention to `xdescribe` and `xit`.

**Comment by bcaudan** [comment]
I've tried to reproduce this behaviour with:
* protractor: 2.1.0 (framework: 'jasmine2')
* jasmine-spec-reporter: 2.2.2

But `xdescribe` are reported as skipped and `xit`are reported as pending.

**Comment by pmowrer** [comment]
@bcaudan Sorry for wasting your time, mistakenly thought I had successfully upgraded to `2.2.2` but was still at `2.1.0`. It works as expected in `2.2.2`, except all the colors are gone :open_mouth:

**Comment by bcaudan** [comment]
are you using grunt-protractor-runner to launch your protractor tests? (https://github.com/bcaudan/jasmine-spec-reporter/issues/36)

**Comment by pmowrer** [comment]
No, I run it directly via node without any such wrappers
