### ISSUE TITLE
[Q] Use with ts-node rather than tsc

### ISSUE THREAD

**Issue by lonix1** [bcaudan/jasmine-spec-reporter#382]
Is it possible to test `.ts` files without first compiling and saving them with `tsc`?

I'm used to other testing tools which don't need to compile and save to disk (before starting the test) so I was wondering if it's possible do the same here? Perhaps to somehow configure it to work with `ts-node`?

**Comment by bcaudan** [comment]
Hi @lonix1, it does not seem related to jasmine-spec-reporter. You should search for ways to run jasmine with ts-node. It seems to have ways to do it, I have never tested it myself though.

**Comment by lonix1** [comment]
Thanks
