### ISSUE TITLE
Stacktrace not shown for some errors

### ISSUE THREAD

**Issue by mik01aj** [bcaudan/jasmine-spec-reporter#42]
When running with default Jasmine reporter, I get this report:

![screenshot 2015-09-01 11 10 28](https://cloud.githubusercontent.com/assets/3027415/9600229/26e3b3e8-509a-11e5-8156-1acfa0f5585d.png)

When running with `jasmine-spec-reporter`, I see (this is only a part of the report):

![screenshot 2015-09-01 11 10 46](https://cloud.githubusercontent.com/assets/3027415/9600244/3db86852-509a-11e5-850d-944b21f1b4a7.png)

The stacktrace is missing. (And it isn't also displayed anywhere else).

**Comment by bcaudan** [comment]
With `jasmine-spec-reporter`, stacktrace are not shown by [default](https://github.com/bcaudan/jasmine-spec-reporter#default-options).

You can enable them by adding the option :
```
{
  displayStacktrace: 'all'
}
```

**Comment by mik01aj** [comment]
Ah, I missed this, thanks!
