### ISSUE TITLE
Is there a way to filter out the console output from the test target?

### ISSUE THREAD

**Issue by nripendra** [bcaudan/jasmine-spec-reporter#45]
The piece of software that I'm currently testing does send a lot of output to the console. Is there a way to configure spec-reporter to ignore those outputs and show the ones only from jasmine. 

Those output may be useful in case of problems but for normal scenarios they just add noise. So, I don't want them completely turned off but rather configured to be turned on/off as desired.

**Comment by bcaudan** [comment]
If these logs are not generated by the reporter, I do not think that it is its responsibility to filter them.

You should consider to configure these logs in you application.

**Comment by nripendra** [comment]
Thanks for response! yes, I surely can change my application. I already have plan for that. I was just asking if it could some how be done and I couldn't find in document :)

Still if possible I think this can be a nice feature, since I don't control every part of my application. Any developer at anytime would be using a lot of 3rd party packages.

I can submit a pull request if it is possible, just let me know which parts should I look into.
