### ISSUE TITLE
Cannot hide pending specs

### ISSUE THREAD

**Issue by Francisc** [bcaudan/jasmine-spec-reporter#46]
Hello,

Running Jasmine with Karma and using spec as the reporter on Windows 8.
Setting the `displayPendingSpec` to `false` as below doesn't get picked up and pending tests are shown:
```
//...
reporters:['spec'],
specRunner:{
   displayPendingSpec:false
},
//...
```

Any idea why that happens?

**Comment by bcaudan** [comment]
You are not at the right place, take a look at https://github.com/mlex/karma-spec-reporter.

**Comment by Francisc** [comment]
Oups, sorry about that.
