### ISSUE TITLE
Return code 0 if spec fail for Jenkins build

### ISSUE THREAD

**Issue by rcbop** [bcaudan/jasmine-spec-reporter#51]
Hello,

I'm currently using this reporter in addition to others in a Jenkins automated build. I would like to know if there any option to configure this reporter so that it won't return shell's error code 1 if a spec fails interrupting the build.

**Comment by bcaudan** [comment]
It is not the responsibility of the reporter. You should probably find this option in your test runner (jasmine-node, protractor, ...).
