### ISSUE TITLE
How to print stack trace ?

### ISSUE THREAD

**Issue by olignyf** [bcaudan/jasmine-spec-reporter#54]
Hi,

Before with jasmine-node I would use --captureExceptions to display the stack trace of exception. How can I do the same with jasmine-spec-reporter ?

![jasmine-no-exceptions-stack](https://cloud.githubusercontent.com/assets/1154566/17116850/954e369c-5287-11e6-8a06-d91e8c572537.png)

Thanks,
Francois

**Comment by bcaudan** [comment]
Hi,

Have a look at the options : https://github.com/bcaudan/jasmine-spec-reporter#default-options

    {
      displayStacktrace: 'none',    // display stacktrace for each failed assertion, values: (all|specs|summary|none)
      ...
