### ISSUE TITLE
Show full stacktrace when expect fails outside the main spec file

### ISSUE THREAD

**Issue by jeniaefimov** [bcaudan/jasmine-spec-reporter#541]
## Bug report

Check with "x":

- [x] I have this issue with the latest release of [jasmine-spec-reporter](https://github.com/bcaudan/jasmine-spec-reporter/releases) 
- [x] I have this issue with the latest release of [jasmine](https://github.com/jasmine/jasmine/releases) 
- [ ] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples)

**Current behavior**

To make `protractor-flake` works correctly it's needed to have a spec file path in **failed spec report** in console, but if `expect` located not in the spec file (but in page object or helper), top line of stacktrace just shows this file, not the spec file that is needed for `protractor-flake` parser to rerun.

![Screenshot 2020-09-24 at 15 59 50](https://user-images.githubusercontent.com/15068752/94155202-fc45f900-fe7e-11ea-95ea-fb2aeb3bfc95.png)

As you can see on screenshot there is no spec file path there.
 
**Expected behavior**

Show whole stacktrace, including entry point (spec file)

Maybe you were thinking about such change? Or maybe you know how to hack report to include spec file path there? (I tried to use custom reporter, but didn't find where to get spec file path)

Thanks

**Comment by bcaudan** [comment]
Hi @jeniaefimov,

Does the stacktrace contain the spec file in the stacktrace when you are not using jasmine-spec-reporter?

if yes, it could be related to the [default stacktrace filtering](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/configuration-parser.ts#L34), you can update the behavior with the corresponding configuration option.

**Comment by jeniaefimov** [comment]
Hey @bcaudan sorry for delay, didn't receive notification, I'll check this way, thanks

**Comment by bcaudan** [comment]
Feel free to reopen if needed
