### ISSUE TITLE
Typo in jasmine-npm-configuration.md

### ISSUE THREAD

**Issue by chrissiedeist** [bcaudan/jasmine-spec-reporter#58]
Noticed a typo in `jasmine-npm-configuration.md`

```node
var jrunner = new Jasmine();
jrunner.configureDefaultReporter({print: noop});    // remove default reporter logs
wrong -- > jasmine.getEnv().addReporter(new SpecReporter());   // add jasmine-spec-reporter
right -- > jrunner.getEnv().addReporter(new SpecReporter());   // add jasmine-spec-reporter
jrunner.loadConfigFile();                           // load jasmine.json configuration
jrunner.execute();
```

**Comment by bcaudan** [comment]
Could you try to clone the repo and run `npm install && npm run example` to reproduce this issue?

[example/run-example.js](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/example/run-example.js) use the same configuration as the doc.

**Comment by JonathanFu** [comment]
@chrissiedeist 
'jasmine' is the global keyword after Jasmine initialization (new Jasmine()).
You can find the logic in node_boot.js.
=> extend(global, jasmineInterface);
include other keywords, e.g. describe, xdescribe, fdescribe, it, xit, fit etc.

So in the above example, it is correct. Also below cases are true.
jrunner.jasmine === jasmine
jrunner.env === jasmine.getEnv()

**Comment by bcaudan** [comment]
OK, the right way seems to be:

    jrunner.addReporter(new SpecReporter());

Jasmine-npm seems to have trouble with reporters since 2.5.0, I will update the doc when it will be stable.
