### ISSUE TITLE
Regression: 'SpecReporter' is not assignable to parameter of type 'CustomReporter'

### ISSUE THREAD

**Issue by squidfunk** [bcaudan/jasmine-spec-reporter#628]
# Issue guidelines

## Bug report

- [x] I have this issue with the latest release of [jasmine-spec-reporter](https://github.com/bcaudan/jasmine-spec-reporter/releases)
- [x] I have this issue with the latest release of [jasmine](https://github.com/jasmine/jasmine/releases)
- [ ] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples)

**Current behavior**

`@types/jasmine` 3.7.2 re-introduces the error fixed in #588, albeit with slightly different outcome:

```
src/execute/index.ts(92,27): error TS2345: Argument of type 'SpecReporter' is not assignable to parameter of type 'CustomReporter'.
  Types of property 'suiteStarted' are incompatible.
    Type '(result: CustomReporterResult) => void' is not assignable to type '(result: SuiteResult, done?: (() => void) | undefined) => void | Promise<void>'.
      Types of parameters 'result' and 'result' are incompatible.
        Type 'SuiteResult' has no properties in common with type 'CustomReporterResult'.
```

**Expected behavior**

No type error, assignment works as expected.

**Minimal reproduction of the problem with instructions**

Package versions:

- `@types/jasmine`: 3.7.2
- `jasmine`: 3.7.0
- `jasmine-spec-reporter`: 7.0.0

``` ts
import Jasmine from "jasmine"
import { SpecReporter, StacktraceOption } from "jasmine-spec-reporter"

const jasmine = new Jasmine({})
jasmine.env.clearReporters()
jasmine.env.addReporter(new SpecReporter({
  spec: { displayStacktrace: StacktraceOption.RAW }
}))
```

**Temporary workaround**:

``` ts 
jasmine.env.addReporter(new SpecReporter({
    spec: { displayStacktrace: StacktraceOption.RAW }
  }) as jasmine.CustomReporter)
```

**Possible fix**

When introspecting the typings, it's pretty clear that the interfaces changed:

`@types/jasmine` / `index.d.ts`

``` ts
interface CustomReporter {
  jasmineStarted?(suiteInfo: JasmineStartedInfo, done?: () => void): void | Promise<void>;
  suiteStarted?(result: SuiteResult, done?: () => void): void | Promise<void>;
  specStarted?(result: SpecResult, done?: () => void): void | Promise<void>;
  specDone?(result: SpecResult, done?: () => void): void | Promise<void>;
  suiteDone?(result: SuiteResult, done?: () => void): void | Promise<void>;
  jasmineDone?(runDetails: JasmineDoneInfo, done?: () => void): void | Promise<void>;
}
```

`jasmine-spec-reporter` / `built/spec-reported.d.ts`

``` ts
export declare class SpecReporter implements CustomReporter {
  ...
  jasmineStarted(suiteInfo: SuiteInfo): void;
  jasmineDone(runDetails: RunDetails): void;
  suiteStarted(result: CustomReporterResult): void;
  suiteDone(result: CustomReporterResult): void;
  specStarted(result: CustomReporterResult): void;
  specDone(result: CustomReporterResult): void;
  private runDetailsToResult;
}
```

**Comment by mikerandall** [comment]
@squidfunk upgrading to version `3.7.4` of `@types/jasmine` fixed this for me.

**Comment by squidfunk** [comment]
@bcaudan I can still reproduce with 3.7.4 which was released 5 hours after I wrote this issue.

**Comment by squidfunk** [comment]
I think this can be closed, as it doesn't happen for me anymore with the following versions:

- `@types/jasmine`: 3.10.2
- `jasmine`: 3.10.0
- `jasmine-spec-reporter`: 7.0.0
