### ISSUE TITLE
Protractor Reporter not following config

### ISSUE THREAD

**Issue by shanep2300** [bcaudan/jasmine-spec-reporter#65]
Hello,

`var SpecReporter = require('jasmine-spec-reporter');
    jasmine.getEnv().addReporter(new SpecReporter({
      displayStacktrace: 'summary',
      displayFailuresSummary: false
    }));`

Doesn't seem to be working anymore. The failures summary still show.

Also, it seems like I'm getting the dot report even though I have `print: function() {}` in the jasmineNodeOpts.

Does this have to do with the newest version of protractor being 4.0.9, at the time of this issue?

**Comment by shanep2300** [comment]
Started an issue at protractor, seeing if it's a problem on their end, or JSP.

https://github.com/angular/protractor/issues/3609

**Comment by OzzyCzech** [comment]
I have same problem

**Comment by shanep2300** [comment]
It looks like this is an issue with Jasmine. Either downgrade to Protractor 4.0.8 or wait until 4.0.11 is released as they downgraded Jasmine until the fix is issued there.
