### ISSUE TITLE
Export Processors in the main module.

### ISSUE THREAD

**Issue by danielesegato** [bcaudan/jasmine-spec-reporter#75]
At this page:
https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/customize-output.md

You suggest to do something like this to write a custom processor:

```javascript
var DisplayProcessor = require('./node_modules/jasmine-spec-reporter/src/display-processor');
```

I think this is bad practice and I think it would be far better to do something like this:

```javascript
// dedicated npm module
var DisplayProcessor = require('jasmine-spec-reporter-processor');
```

or

```javascript
var SpecReporter =  require('jasmine-spec-reporter-processor');
// accessor from main module
var DisplayProcessor = SpecReporter.newDisplayProcessor();
```

**Comment by bcaudan** [comment]
Actually, I'm working on a refactoring and I choose to expose both SpecReporter and DisplayProcessor from the main module:
```js
var SpecReporter =  require('jasmine-spec-reporter').SpecReporter;
var DisplayProcessor = require('jasmine-spec-reporter').DisplayProcessor;
```

**Comment by danielesegato** [comment]
Awesome! Thanks you!
