### ISSUE TITLE
Switch to yarn

### ISSUE THREAD

**Issue by bcaudan** [bcaudan/jasmine-spec-reporter#98]

**Comment by bcaudan** [comment]
Due to https://github.com/yarnpkg/yarn/issues/2165, integration tests could work correctly only if yarn cache is cleared. This workaround loses the benefits of this switch. So wait for resolution before going further.

**Comment by bcaudan** [comment]
https://github.com/yarnpkg/yarn/issues/2165#issuecomment-285113259 could do the trick

**Comment by johnjbarton** [comment]
I gather that yarn cannot be set at as a dev dependency and must be installed globally?

**Comment by bcaudan** [comment]
yes, cf https://yarnpkg.com/en/docs/install
